### PR TITLE
Fix PlatformIO support, version update

### LINKED ISSUE #5: digitalWriteFast does not import properly in PlatformIO
Recently I was involved with porting some projects from Arduino IDE over to PlatformIO. I noticed that originally when this was done, PlatformIO had been set to use the library `watterott/digitalWriteFast@^1.0.0`. This obviously is wrong, so I changed it to `arminjo/digitalWriteFast@^1.2.0`. However, upon doing so, the library does not install properly once called. Most importantly the actual `digitalWriteFast.h` file is not actually included with the library:

drffiles

I believe this may be due to a malformed library.json file and have opened a PR to update said file.

### PR DESCRIPTION
**Pull request by nomakewan**
Updates the library.json file to fix compatibility with PlatformIO. Also updates the library.properties file to 1.2.1 as well in preparation for a new release.

Resolves #5

### CODE REVIEW

**Comment by ArminJo** [comment]
Thanks for reporting 👍 !
Can you check the latest version / do a QS, before I will make a release?

**Comment by nomakewan** [comment]
> Thanks for reporting 👍 ! Can you check the latest version / do a QS, before I will make a release?

I ran `pio pkg pack` on the local directory and it correctly parsed the new JSON, giving it the following package result:

piopkg

So this appears to have fixed the issue. As for the issue with your build failing, that is because DrAzzy and SSL certificate renewals do not get along with one another. While I can fix the manifest file very easily (and have), the ATTiny toolchain is _also_ hosted on his private website rather than Github, and so unfortunately suffers from the same SSL certificate expiration.

**Comment by nomakewan** [comment]
As one last follow-up, I just tested my PlatformIO build against 1.2.1 and it worked perfectly! Thank you very much for the swift fix.

**Comment by ArminJo** [comment]
Thanks for feedback, I personally do not use PlatformIO, and cannot make such tests!

**Pull request merged**
